### ISSUE TITLE
dokku_config don't set strings with python3

### ISSUE THREAD

**Issue by mehdibechiri** [dokku/ansible-dokku#13]
# Description of problem
dokku_config library doesn't allow me to set two string variables

# Environment
dokku_ansible: `latest`
ansible: `2.7.8`
remote_host: `Ubuntu bionic` (tested on `Ubuntu xenial` too)
remote_host python version: `3.6.7` (`3.5.2` on xenial)

If worth the precision, playbook is run with Packer on an AWS instance.

# Steps to Reproduce
Run the following playbook:
```
---
- hosts: all
  gather_facts: true
  roles:
    - { role: dokku, become: yes }
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    dokku_plugins:
      - name: mariadb
        url: https://github.com/dokku/dokku-mariadb.git
      - name: memcached
        url: https://github.com/dokku/dokku-memcached.git
      - name: clone
        url: https://github.com/crisward/dokku-clone.git
    dokku_hostname: "my_app-uat"
    dokku_key_file: "/home/ubuntu/.ssh/id_rsa.pub"
    plugn_version: "0.3.2"
  tasks:
    - name: echo var
      debug:
        msg: "{{ ansible_hostname }},{{ ansible_user }},{{ansible_env.HOME}}"

    - name: Create a dokku app
      dokku_app:
        app: my_app

    - name: clone a repo
      dokku_clone:
        app: my_app
        repository: /home/ubuntu/my_app

    - name: mariadb:create my_appdb
      dokku_service_create:
        name: my_appdb
        service: mariadb

    - name: memcached:create my_appmem
      dokku_service_create:
        name: my_appmem
        service: memcached

    - name: mariadb:link my_appdb my_app
      dokku_service_link:
        app: my_app
        name: my_appdb
        service: mariadb

    - name: memcached:link my_appmem my_app
      dokku_service_link:
        app: my_app
        name: my_appmem
        service: memcached

    - name: create /var/www/my_app/signatures
      file:
        path: /var/www/my_app/signatures
        state: directory
        mode: 0755
        owner: dokku
        group: ubuntu
      become: yes
      become_user: root
      become_method: sudo

    - name: create /var/www/my_app/uploads
      file:
        path: /var/www/my_app/uploads
        state: directory
        mode: 0755
        owner: dokku
        group: ubuntu
      become: yes
      become_user: root
      become_method: sudo

    - name: mount /var/www/my_app/signatures
      dokku_storage:
        app: my_app
        mounts:
          - /var/www/my_app/signatures:/app/public/generator/signature

    - name: mount /var/www/my_app/uploads
      dokku_storage:
        app: my_app
        mounts:
          - /var/www/my_app/uploads:/app/public/uploads

    - name: set ROOT_URL and SECURITY_KEY
      dokku_config:
        app: my_app
        config:
          ROOT_URL: "https://my_app-uat.io"
          SECURITY_KEY: "uiopkljhulmnbjhuiojklmnbhjuij"

    - name: domains:add my_app my_app-uat.io
      dokku_domains:
        app: my_app
        domains:
          - my_app-uat.io

    - name: delete ubuntu keys
      file:
        path: /home/ubuntu/.ssh
        state: absent

    - name: delete dokku keys
      file:
        path: /home/dokku/.ssh
        state: absent
      become: yes
      become_user: root
      become_method: sudo

```

# Current Results
```
amazon-ebs: TASK [set ROOT_URL and SECURITY_KEY] *******************************************
amazon-ebs: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SyntaxError: invalid syntax
amazon-ebs: fatal: [default]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```
_Editing with full traceback:_
```
    amazon-ebs: <127.0.0.1> (0, 'ansible-tmp-1557838276.54-73536548663637=~ec2-user/.ansible/tmp/ansible-tmp-1557838276.54-73536548663637\n', '')
    amazon-ebs: The full traceback is:
    amazon-ebs: Traceback (most recent call last):
    amazon-ebs:   File "/Library/Python/2.7/site-packages/ansible/executor/task_executor.py", line 140, in run
    amazon-ebs:     res = self._execute()
    amazon-ebs:   File "/Library/Python/2.7/site-packages/ansible/executor/task_executor.py", line 612, in _execute
    amazon-ebs:     result = self._handler.run(task_vars=variables)
    amazon-ebs:   File "/Library/Python/2.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
    amazon-ebs:     result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
    amazon-ebs:   File "/Library/Python/2.7/site-packages/ansible/plugins/action/__init__.py", line 742, in _execute_module
    amazon-ebs:     (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
    amazon-ebs:   File "/Library/Python/2.7/site-packages/ansible/plugins/action/__init__.py", line 178, in _configure_module
    amazon-ebs:     environment=final_environment)
    amazon-ebs:   File "/Library/Python/2.7/site-packages/ansible/executor/module_common.py", line 973, in modify_module
    amazon-ebs:     environment=environment)
    amazon-ebs:   File "/Library/Python/2.7/site-packages/ansible/executor/module_common.py", line 791, in _find_module_utils
    amazon-ebs:     recursive_finder(module_name, b_module_data, py_module_names, py_module_cache, zf)
    amazon-ebs:   File "/Library/Python/2.7/site-packages/ansible/executor/module_common.py", line 538, in recursive_finder
    amazon-ebs:     tree = ast.parse(data)
    amazon-ebs:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    amazon-ebs:     return compile(source, filename, mode, PyCF_ONLY_AST)
    amazon-ebs:   File "<unknown>", line 1
    amazon-ebs:     Skip to content
    amazon-ebs:           ^
    amazon-ebs: SyntaxError: invalid syntax
    amazon-ebs: fatal: [default]: FAILED! => {
    amazon-ebs:     "msg": "Unexpected failure during module execution.",
    amazon-ebs:     "stdout": ""
    amazon-ebs: }
```

# Expected Results
The library should assign values and return 0.
```
amazon-ebs: TASK [set ROOT_URL and SECURITY_KEY] ******************************************************
amazon-ebs: changed: [default]
```

**Comment by josegonzalez** [comment]
Fixed in https://github.com/dokku/ansible-dokku/commit/b5d34d9aa9f0fb1e1574c02eaec3c4da5f4d51ab#diff-1bf08466b79571e460eb21b39b7f8cdd
